name: Parallel Build
on: push
jobs:
  Add-To-Cart-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCartTest

      - name: Cypress Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Rpoert - Add to Cart
          path: cypress/reports/html

  Reg-Flow-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:registerFlow

      - name: Cypress Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Rpoert - Reg Flow
          path: cypress/reports/html